### ISSUE TITLE
Implement logic to export into CSV

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/fit-geojson-vuejs#34]
Implement logic to export data uploaded into CSV .
We will need a UI to allow to the user to select the export format (Geojson - default- , or CSV).

**Comment by YasiOnFire** [comment]
Hey, may i try this one please?

**Comment by roberto-butti** [comment]
@YasiOnFire  sure! Thank you!
In Fit.vue file as a Vue component we have the data object with geojson attribute (this.geojson). That geojson is produced by fit and gpx parsing. I think that we need to parse that geojson and export to csv.
Each row of csv could be a point . If you take a look on geojson you will se a list fo Features.
![Screenshot 2019-10-07 at 09 03 34](https://user-images.githubusercontent.com/678434/66291157-69b0f080-e8e1-11e9-864a-8e36e6157083.png)

Each Feature has 2 elements, properties and geometry.
For lat and long (2 mandatory column for CSV) you can take geometry.coordinates[0].
For other columns of CSV you can take properties object. As object could be nested you can flat all properties.

**Comment by roberto-butti** [comment]
Thank you @YasiOnFire ! Great implementation. Merged!
