### ISSUE TITLE
UI for export format Selection

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/fit-geojson-vuejs#35]
Once #34  is implemented we need a UI to allow to the user to select the export format.
The default is geojson (so it doesn't have impact on the UX).
Add a UI component (select, radio ...) to select export format

**Comment by mtrunt** [comment]
I can take a look on this if that's ok.

**Comment by roberto-butti** [comment]
Sure, @mtrunt ! Thank you! Do you have some ideas or suggestions about the UI design? We don't have in the UI some component to collect user preferences

**Comment by mtrunt** [comment]
Let me play with it for a bit.

@roberto-butti Do you have a file that can be shared in the meantime? I tried with a couple I have but got some errors; will try to debug it later.

**Comment by roberto-butti** [comment]
> Let me play with it for a bit.
> 
> @roberto-butti Do you have a file that can be shared in the meantime? I tried with a couple I have but got some errors; will try to debug it later.

You can use this public GPX file. It is a route of a public trail running race.
https://www.barabinarun.com/images/BarabinaRun_5_ottobre_2019_ore_15_Official.gpx
Let me know about the error that you see in the JavaScript Console.

**Comment by mtrunt** [comment]
@roberto-butti I believe my files were corrupted, that GPX worked fine.
Been playing with it and here are a couple suggestions.

I like the one with the dropdown more but may need to use a library for the dropdown.

Button for each type:
![image](https://user-images.githubusercontent.com/1170107/66261423-960a2700-e792-11e9-857e-a02aef086d96.png)

Dropdown:
![image](https://user-images.githubusercontent.com/1170107/66261439-d5d10e80-e792-11e9-9f57-c530530edada.png)

What you think?

**Comment by roberto-butti** [comment]
Hi @mtrunt , thank you for your job! 
I think that dropdown solution is cleaner and more scalable ( if on the future we will add new option). I like it!!!!

**Comment by mtrunt** [comment]
@roberto-butti submitted #42. Any thoughts?

**Comment by roberto-butti** [comment]
> @roberto-butti submitted #42. Any thoughts?

@mtrunt great Work, i merged it. But i have some conflict on Fit.vue file so i need to merge manually.
I would like to open issues for some small improvement (but I would like to know your point of view):
- Update the Download label based on "selectedFormat", so the user will read "Download Geojson" or "Download CSV "
- Hide CSV label until the CSV export will be implemented OR display a message "CSV is not yet implemented, you are downloading a Geojson file"

What do you think ?
In order to have your commit in the commit history list I suggest you to pull and update your local code before to request a pull request, because i think that in the meanwhile you did the work we merged other pull request so we had some conflicts on Fit.vue. Thank you!

**Comment by mtrunt** [comment]
I was also thinking on this to make it clearer to the user but I was afraid the button would be too long. Let me try some things.
> * Update the Download label based on "selectedFormat", so the user will read "Download Geojson" or "Download CSV "

I'll hide the CSV option in the meantime.
> * Hide CSV label until the CSV export will be implemented OR display a message "CSV is not yet implemented, you are downloading a Geojson file"


Oh that's nice, I'll update my local before the next PR.
> In order to have your commit in the commit history list I suggest you to pull and update your local code before to request a pull request, because i think that in the meanwhile you did the work we merged other pull request so we had some conflicts on Fit.vue. Thank you!
