### ISSUE TITLE
UI for Error/info messages

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/fit-geojson-vuejs#37]
The User needs to see some feedback when he uploads a not valid file.
Better UI for error messages (url not valid or file upload is not the correct format)

**Comment by mountainash** [comment]
The error UI is needed, but I'm also looking into adding support for restricting the file picker to only allowing supported file types. It looks like it should be possible using https://www.dropzonejs.com/#config-acceptedFiles

**Comment by roberto-butti** [comment]
> The error UI is needed, but I'm also looking into adding support for restricting the file picker to only allowing supported file types. It looks like it should be possible using https://www.dropzonejs.com/#config-acceptedFiles

I agree with you @mountainash  to make the validation stronger.
Just for your information, we are using vue2-dropzone package for using dropzone into Vue. Maybe is useful to know how to send to dropzone the acceptedFiles config parameter.

I will open a new issue, because anyway, we need a better message system for the user.

**Comment by mountainash** [comment]
Agreed - both are separate.

I'm installing the project now and will attempt to solve both issues.
