### ISSUE TITLE
UI: reduce the margin under the Fit2Geojson logo

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/fit-geojson-vuejs#43]
<img width="630" alt="Screenshot 2019-10-06 at 09 23 16" src="https://user-images.githubusercontent.com/678434/66265712-183e2e00-e81b-11e9-8d1c-1fac68468515.png">

**Comment by ShradhaSangtani** [comment]
@roberto-butti I would like to work on this

**Comment by ShradhaSangtani** [comment]
I am able to reduce the margin under Fit2Geojson logo and it looks like this - 
![image](https://user-images.githubusercontent.com/14348823/66266198-4897c380-e83f-11e9-86a4-fd39cee5e218.png)
Let me know if this is fine? I will raise a PR soon.

**Comment by bryancresswell** [comment]
Have also done a PR, reduced margin by 10-fold, down to 5 px so at least that there is still a bit of spacing between the two elements.

**Comment by ShradhaSangtani** [comment]
@bryancresswell Was making the same change. Just reduced the top margin to 0px instead of 5px. @roberto-butti Let me know if there is something else to pick up :)

**Comment by roberto-butti** [comment]
great work @bryancresswell  and @ShradhaSangtani 
I merge with 5px.
I will take a look if there are some side effects.
I will consider your suggestion @ShradhaSangtani  for 0px.

**Comment by roberto-butti** [comment]
> @roberto-butti Let me know if there is something else to pick up :)

 I opened #49 @ShradhaSangtani
