### ISSUE TITLE
UI: Update the Download label

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/fit-geojson-vuejs#44]
Update the Download label based on "selectedFormat", so the user will read "Download Geojson" or "Download CSV "
<img width="359" alt="Screenshot 2019-10-06 at 09 25 52" src="https://user-images.githubusercontent.com/678434/66265725-6e12d600-e81b-11e9-8faa-2273503e9607.png">

**Comment by kaushikikrityy** [comment]
Can you please direct me to the file where this label is present?

**Comment by roberto-butti** [comment]
ok @kaushikikrityy , try to take a look on Fit.vue file, look for btn-download

**Comment by roberto-butti** [comment]
Hi @kaushikikrityy  this is was closed now by the pull request #62  related to another issue, but it included also the implementation of this issue

**Comment by mtrunt** [comment]
@roberto-butti Adding to this issue. What you think of this?
![image](https://user-images.githubusercontent.com/1170107/66321258-e8a82800-e8e5-11e9-9811-b9fe8c64b871.png)

**Comment by roberto-butti** [comment]
This is great I will open a new issues for changing the label, because the logic for reactive update is yet implemented.
