### ISSUE TITLE
UI: increment margin between codemirror and btn-download

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/fit-geojson-vuejs#45]
<img width="367" alt="Screenshot 2019-10-06 at 09 37 48" src="https://user-images.githubusercontent.com/678434/66265821-0bbad500-e81d-11e9-8da6-316756690f05.png">

**Comment by learnerjay** [comment]
i will like to work on it.

**Comment by roberto-butti** [comment]
ok @learnerjay thank you! i suggest to add a class to a div after codemirror

<img width="522" alt="Screenshot 2019-10-06 at 09 50 27" src="https://user-images.githubusercontent.com/678434/66265955-cdbeb080-e81e-11e9-95f6-04ec8656348d.png">

**Comment by roberto-butti** [comment]
@learnerjay  , just to know. Did you take in charge the issue?
Just to know if you can do it, or you need some additional informations.
Thank you!

**Comment by roberto-butti** [comment]
closed by @mtrunt  in #65
