### ISSUE TITLE
Error message is hiding the upload button

### ISSUE THREAD

**Issue by ShradhaSangtani** [roberto-butti/fit-geojson-vuejs#48]
![image](https://user-images.githubusercontent.com/14348823/66267028-d7114280-e849-11e9-81fc-948dfbd188e4.png)

When no file or incorrect file is uploaded, the error message is displayed at the top. This hides the download button and user would have to scroll down to upload another file. This is not user intuitive.

**Comment by roberto-butti** [comment]
Great feedback.
Do you have any suggestion?
I was thinking to reserve a small area always dispalyed, to show any information. If you take a look in the code we have status variable where we store any kind of information useful for the user but never displayed.
We could identinfy some type of message as "info", "warn" , "error" and dispaly it in the reserved DIV. 
What do you think @ShradhaSangtani ? Or you have more brillant ideas?

**Comment by ShradhaSangtani** [comment]
@roberto-butti I see that we already have a reserved error DIV inside content DIV where the error message is displayed currently. 
So the solution could be to adjust the size of all the elements in content DIV so that they don't move when error message pops up.
Something like this -
**Before error message** 
![image](https://user-images.githubusercontent.com/14348823/66267350-784dc800-e84d-11e9-9732-2845bc8b8a87.png)


**After error message**
![image](https://user-images.githubusercontent.com/14348823/66267335-6409cb00-e84d-11e9-86dd-060fdb874e66.png)
