### ISSUE TITLE
UI: reduce height of header

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/fit-geojson-vuejs#49]
- [ ] reduce height of header (class header)
- [ ] reduce the dimension of svg logo (class logo)

**Comment by ShradhaSangtani** [comment]
@roberto-butti I would like to work on this

**Comment by ShradhaSangtani** [comment]
![image](https://user-images.githubusercontent.com/14348823/66267768-ecd73580-e852-11e9-9770-5c743bbc9167.png)

@roberto-butti Implemented both tasks. The page would look like this after the change. Let me know if any dimension requires changes.
