### ISSUE TITLE
UI: reduce height of footer

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/fit-geojson-vuejs#54]
suggestion are appreciated

**Comment by ShradhaSangtani** [comment]
@roberto-butti Reducing the height of footer would increase the gap between upload button and footer. Do you intend to put anything there?

**Comment by ShradhaSangtani** [comment]
I have raised a PR, the UI would look like this after removing the margin from footer -
![image](https://user-images.githubusercontent.com/14348823/66268242-1c893c00-e859-11e9-958a-a89785824e88.png)

**Comment by roberto-butti** [comment]
thank you @ShradhaSangtani  
close #56
