### ISSUE TITLE
UI: changing label for Export/Download button

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/fit-geojson-vuejs#64]
As suggested by @mtrunt we need to change the CTA on download button
![66321258-e8a82800-e8e5-11e9-9811-b9fe8c64b871](https://user-images.githubusercontent.com/678434/66323893-cda8d880-e924-11e9-929b-0a9bc0a42b9c.png)

**Comment by mtrunt** [comment]
I'll make a PR with the changes.

What you mean with the logic for reactive update? Maybe I can also do that or take it into consideration.

**Comment by roberto-butti** [comment]
In Fit.vue file you have
`DOWNLOAD {{ selectedFormat.toUpperCase() }}`
The code in the braces, it depends on the value you select (geojson or csv). This is reactive update.
I think that is enough to put before the div tag "Download as"  and edit the braces into:
`{{ selectedFormat.toUpperCase() }}`

**Comment by roberto-butti** [comment]
thank you @mtrunt
