### ISSUE TITLE
UI: create banner for promote Hacktoberfest

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/fit-geojson-vuejs#66]
**Fit2Geojsn** will be presented in an **Hacktoberfest** Event ([https://hacktoberfest.digitalocean.com/events](https://hacktoberfest.digitalocean.com/events) in Italy. For this reason we would like to promote the event creating a link in the home page (maybe in the footer).

The event in North East Italy [https://www.eventbrite.it/e/biglietti-hacktoberfest-in-h-farm-75475488217](https://www.eventbrite.it/e/biglietti-hacktoberfest-in-h-farm-75475488217)

**Comment by mountainash** [comment]
I'll take this. Anything in particular you want it to say? Or just look generally #Hacktoberfest2019-ish?

**Comment by roberto-butti** [comment]
I think that could be a CTA to
https://hacktoberfest.digitalocean.com/ in the footer.
Maybe in the header we could have an additional CTA to local event:
[Open some Pull Request with us at Hacktoberfest Event in Italy on 22th October](https://www.eventbrite.it/e/biglietti-hacktoberfest-in-h-farm-754).

Do yuo think that is too much?

**Comment by mountainash** [comment]
Too much. I have something looking good now - must I need to fight with the restrictive and unnatural (for me) linting. Will commit soon.

**Comment by mountainash** [comment]
Closed in Merge #68 ?

**Comment by roberto-butti** [comment]
Yes closed. Thank you!!! I will remove the banner once Hacktoberfest is completed.
Thank you @mountainash !!!
