### ISSUE TITLE
Auto-Generate CONTRIBUTORS.md

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/fit-geojson-vuejs#79]
Create a Nodejs script in script directory named contributors.js that:
- calls https://api.github.com/repos/roberto-butti/fit-geojson-vuejs/contributors
- with the response (if status code 200) obtain a js object considering the format: https://developer.github.com/v3/repos/#response-if-repository-contains-content
- generate a CONTRIBUTORS.md:

To generate CONTRIBUTORS.md:
- filter only items type == "User"
- display login, avatar_url, html_url, contributions and site_admin

**Comment by ahmadbilaldev** [comment]
I would like to work on this.

**Comment by ahmadbilaldev** [comment]
> generate a CONTRIBUTORS.md:

Can you shed more light on the generation of CONTRIBUTORS.md?

**Comment by roberto-butti** [comment]
im' going to close this, thanks to @gcoro .
It works like a charm!
