### ISSUE TITLE
remove promo banner for Hacktoberfest event (was on 22th october)

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/fit-geojson-vuejs#98]
Remove banner in App.vue file.
The banner is included in the div:
`div id="banner"`

Be sure to "clean" also css styles related to banner class.

**Comment by adriaanvermeire** [comment]
Can I work on this?

**Comment by roberto-butti** [comment]
Sure! ;) thank you!

**Comment by Theo-Dgl** [comment]
Oh! Sorry I didn't see that this issue was assigned.

**Comment by adriaanvermeire** [comment]
No worries! @Theo-Dgl
